        
# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ master, construction ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7']
        julia-version: ['1.3']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up Julia ${{ matrix.julia-version }}
      uses: julia-actions/setup-julia@v1
      with:
        version: ${{ matrix.julia-version }}
    - name: Install dependencies
      run: |
        python --version
        julia --version
        julia pomato/_installation/julia_install_from_git.jl
        pip install pytest-cov 
        pip install pytest==4.6
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        pytest --durations=0 --cov=./ --cov-report=xml
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1